version: '3'

volumes:
  allure-docker-service:
    driver: local

services:
  allure-docker-service-ui:
    build:
      context: ../allure-docker-service-ui
      dockerfile: docker/Dockerfile.bionic
      args:
        BUILD_DATE: "na"
        VERSION: "na"
        VCS_REF: "na"
    environment:
      ALLURE_DOCKER_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_API_URL_PREFIX: ""
      URL_PREFIX: ""
    ports:
      - "5252:5252"
